### ISSUE TITLE
error

### ISSUE THREAD

**Issue by darekmer** [RomainOdeval/batflat#12]
php 8.1
error: Fatal error: Null can not be used as a standalone type in /var/www/html/batflat-test/inc/core/lib/Templates.php on line 267

**Comment by WebCrew** [comment]
Here you can find some info about the issue:
https://php.watch/versions/8.2/null-false-types 

In **PHP 8.2** and later, using **null** and **false** as standalone types **is allowed**.

**Comment by RomainOdeval** [comment]
Sorry @darekmer , the last commit compatible with PHP 7.4+ is https://github.com/RomainOdeval/batflat/commit/8c55992fcac03ea189cffde00026d85b819fd265

After that, Batflat is compatible with PHP 8.2+ only.
I had no plan to do a version compatible with PHP 8.1 strict.
You must update your PHP version.

After some changes, il will create releases to clarify this but it's a lot of work.
Thank you for your understanding, il will close this issue.
